[project]
name = "aaronimbrock.com"
version = "0.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandoc>=2.4",
]

[dependency-groups]
dev = [
    "frontmatter>=3.0.8",
    "pandoc>=2.4",
    "ruff>=0.9.1",
]
