name: Checkout

on: [push]

jobs:
 checkout-action:
  runs-on: ubuntu-latest
  steps:
    - name: Export System Vars
      run: exportr
    - name: List files Before
      run: ls -lah
    - uses: actions/checkout@v4.1.7
    - name: List files after
      run: ls -lah
