name: Checkout

on:
  push:
    branches:
      - main

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: List files after
        run: ls -lah
      - name: Remove extras
        run: |
          mv html/html temp
          mv temp html
          ls -lah
